# Generated by Django 3.2.15 on 2023-06-14 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('dba', models.CharField(blank=True, max_length=128, null=True)),
                ('full_name', models.CharField(blank=True, max_length=128, null=True)),
                ('usdot', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=128, null=True)),
                ('extra_phone_number', models.CharField(blank=True, max_length=128, null=True)),
                ('phone_number_2', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('extra_emails', models.EmailField(blank=True, max_length=128, null=True)),
                ('email_2', models.EmailField(blank=True, max_length=128, null=True)),
                ('ssn', models.CharField(blank=True, max_length=128, null=True)),
                ('ein', models.CharField(blank=True, max_length=128, null=True)),
                ('mc_number', models.CharField(blank=True, max_length=128, null=True)),
                ('pin_number', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('address_2', models.CharField(blank=True, max_length=256, null=True)),
                ('zip', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('featured_image', models.ImageField(blank=True, default='service/no-img.png', null=True, upload_to='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=128, null=True)),
                ('role', models.CharField(blank=True, max_length=128, null=True)),
                ('ssn', models.CharField(blank=True, max_length=128, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=128, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=128, null=True)),
                ('license', models.CharField(blank=True, max_length=128, null=True)),
                ('license_type', models.CharField(blank=True, max_length=128, null=True)),
                ('license_expiration', models.DateField(blank=True, null=True)),
                ('license_zip', models.CharField(blank=True, max_length=128, null=True)),
                ('license_state', models.CharField(blank=True, max_length=128, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=128, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=128, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('on_leave', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.company')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalTestCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalTestForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerEmployeeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(blank=True, choices=[('alert', 'alert'), ('simple_notification', 'simple_notification')], max_length=128, null=True)),
                ('notification', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_document_type', models.CharField(blank=True, choices=[('license', 'license'), ('dot_drug_test', 'dot_drug_test'), ('none', 'none')], max_length=128, null=True)),
                ('notification_file_type', models.CharField(blank=True, choices=[('image', 'image'), ('pdf', 'pdf'), ('docx', 'docx')], max_length=128, null=True)),
                ('notification_file', models.FileField(blank=True, null=True, upload_to='')),
                ('notification_accept', models.BooleanField(default=False)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.company')),
                ('notification_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.employee')),
                ('notification_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('file_for', models.CharField(blank=True, choices=[('license', 'license'), ('dot_drug_test', 'dot_drug_test')], max_length=128, null=True)),
                ('file_type', models.CharField(blank=True, choices=[('image', 'image'), ('pdf', 'pdf'), ('docx', 'docx')], max_length=128, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('two_day_before_expiration', models.DateField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('non_expiration_type', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DotDrugTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(blank=True, choices=[('urine_drug_test', 'urine_drug_test'), ('urine_drug_breathe_test', 'urine_drug_breathe_test')], max_length=128, null=True)),
                ('dot_federal', models.CharField(blank=True, choices=[('dot_test', 'dot_test')], default='dot_test', max_length=128, null=True)),
                ('test_reason', models.CharField(blank=True, choices=[('pre_employment', 'pre_employment'), ('random', 'random'), ('post_accident', 'post_accident'), ('reasonable_suspicion', 'reasonable_suspicion'), ('return_to_duty', 'return_to_duty'), ('follow_up', 'follow_up'), ('stipulated_agreement', 'stipulated_agreement'), ('phys_periodic', 'phys_periodic')], default='random', max_length=128, null=True)),
                ('panel', models.CharField(blank=True, choices=[('5_panel_dot_test', '5_panel_dot_test')], default='5_panel_dot_test', max_length=128, null=True)),
                ('observer', models.CharField(blank=True, choices=[('no_observer', 'no_observer')], default='no_observer', max_length=128, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=128, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('scheduled_at', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.employee')),
                ('medical_test_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.medicaltestcenters')),
            ],
        ),
    ]
