# Generated by Django 3.2.15 on 2023-06-14 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalTestCenters',
            new_name='MedicalTestCenter',
        ),
        migrations.RenameModel(
            old_name='MedicalTestForms',
            new_name='MedicalTestForm',
        ),
    ]
